### ISSUE TITLE
h5py v2.8.0 breaks unit tests

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPy#100]
unit tests since h5py 2.8.0 break!
```
======================================================================
ERROR: test_Network_03 (LFPy.test.test_network.testNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ehagen/Repositories/LFPy/LFPy/test/test_network.py", line 340, in test_Network_03
    file_name='OUTPUT.h5')
  File "/Users/ehagen/Repositories/LFPy/LFPy/network.py", line 1054, in simulate
    COMM.Reduce(value.value, recvbuf, op=op, root=0)
  File "mpi4py/MPI/Comm.pyx", line 703, in mpi4py.MPI.Comm.Reduce
  File "mpi4py/MPI/msgbuffer.pxi", line 665, in mpi4py.MPI._p_msg_cco.for_reduce
  File "mpi4py/MPI/msgbuffer.pxi", line 634, in mpi4py.MPI._p_msg_cco.for_cro_send
  File "mpi4py/MPI/msgbuffer.pxi", line 155, in mpi4py.MPI.message_simple
  File "mpi4py/MPI/msgbuffer.pxi", line 101, in mpi4py.MPI.message_basic
KeyError: '<d'
-------------------- >> begin captured stdout << ---------------------
Connected population test to test by 7 connections and 30 synapses
t = 100.0 ms

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_Network_04 (LFPy.test.test_network.testNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ehagen/Repositories/LFPy/LFPy/test/test_network.py", line 398, in test_Network_04
    network.create_population(**populationParameters)
  File "/Users/ehagen/Repositories/LFPy/LFPy/network.py", line 601, in create_population
    self.pc.set_gid2node(gid, RANK)
RuntimeError: hoc error

----------------------------------------------------------------------
Ran 279 tests in 82.445s

FAILED (errors=2)
```

One quick fix is to force h5py <2.8 upon install, another is to replace with e.g., exdir (http://exdir.rtfd.io)

**Comment by espenhgn** [comment]
PR #99 should fix this issue. Caused by `MPI.Reduce` call with `sendbuf dtype float`, and not `np.float` dtype. Not sure about the reason for this. Will close.
