### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPy#47]
Could ease install of LFPy if NEURON is also available

**Comment by espenhgn** [comment]
Should give this priority as NEURON is now indeed on conda-forge: https://anaconda.org/conda-forge/neuron. 

Should be possible to get automatic deposits with conda-recipe, see exdir for example: https://github.com/CINPLA/exdir/tree/dev/.conda-recipe, as well as https://conda.io/projects/conda-build/en/latest/index.html

**Comment by espenhgn** [comment]
Did some testing. Neuron as currently provided on conda-forge lacks bindings to MPI (openmpi), so it will not work with LFPy for the time being (tested with clean Ubuntu 18.04, conda-4.6.11, python-3.7, neuron-7.6.5):
```
$ ldd /home/lfpy/anaconda3/envs/lfpy/bin/nrniv
	linux-vdso.so.1 (0x00007fffa8bb7000)
	libnrnoc.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libnrnoc.so.0 (0x00007f4c85c1f000)
	libnrniv.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libnrniv.so.0 (0x00007f4c85b2f000)
	libivoc.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libivoc.so.0 (0x00007f4c85aed000)
	liboc.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/liboc.so.0 (0x00007f4c85ab9000)
	libnrnmpi.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libnrnmpi.so.0 (0x00007f4c85ab4000)
	libneuron_gnu.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libneuron_gnu.so.0 (0x00007f4c85aa3000)
	libscopmath.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libscopmath.so.0 (0x00007f4c85a35000)
	libsparse13.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libsparse13.so.0 (0x00007f4c85a89000)
	libsundials.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libsundials.so.0 (0x00007f4c859fd000)
	libmemacs.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libmemacs.so.0 (0x00007f4c859e3000)
	libmeschach.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libmeschach.so.0 (0x00007f4c85988000)
	libivos.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libivos.so.0 (0x00007f4c85976000)
	libnrnpython.so.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libnrnpython.so.0 (0x00007f4c85942000)
	libpython3.7m.so.1.0 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libpython3.7m.so.1.0 (0x00007f4c855db000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4c853a8000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f4c851a5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4c84f9d000)
	libreadline.so.7 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libreadline.so.7 (0x00007f4c84f4c000)
	libncurses.so.6 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libncurses.so.6 (0x00007f4c84f1f000)
	libtinfo.so.6 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libtinfo.so.6 (0x00007f4c84ee2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4c84cde000)
	libstdc++.so.6 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libstdc++.so.6 (0x00007f4c84b9d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4c847ff000)
	libgcc_s.so.1 => /home/lfpy/anaconda3/envs/lfpy/bin/../lib/libgcc_s.so.1 (0x00007f4c847ea000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4c843f7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4c85a5f000)
```
Some conda build and environment files have been pushed to https://github.com/espenhgn/LFPy/tree/fix_47, but they don't work as intended and I won't investigate further:
```
(base) lfpy@lfpy-VirtualBox:~/LFPy$ conda-build .conda-recipe/. --python=3.7 -c conda-forge
WARNING: The conda.compat module is deprecated and will be removed in a future release.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 0 (delta 0)
Unpacking objects: 100% (4/4), done.
From /home/lfpy/LFPy
 * [new ref]                    -> _conda_cache_origin_head
Cloning into '/home/lfpy/anaconda3/conda-bld/lfpy_1554888800821/work'...
done.
checkout: 'HEAD'
Your branch is up to date with 'origin/_conda_cache_origin_head'.
==> git log -n1 <==

commit 26c03be531848cdae6f55163a53ddc0f5b73a503
Author: XXXX XXXXX <XXXXX@XXXX.XX>
Date:   Wed Apr 10 11:28:31 2019 +0200

    prep merge

==> git describe --tags --dirty <==

v2.0.2-8-g26c03be

==> git status <==

On branch _conda_cache_origin_head
Your branch is up to date with 'origin/_conda_cache_origin_head'.

nothing to commit, working tree clean

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
Attempting to finalize metadata for lfpy
INFO:conda_build.metadata:Attempting to finalize metadata for lfpy
Collecting package metadata: ...working... done
Solving environment: ...working... done
BUILD START: ['lfpy-0.0.0_custom-pyh39e3cac_0.tar.bz2']
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /home/lfpy/anaconda3/conda-bld/work 
  Test:
 /home/lfpy/anaconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/lfpy/anaconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac 
  Build:
source activate  /home/lfpy/anaconda3/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda_build/environ.py", line 753, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/plan.py", line 473, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 107, in solve_for_transaction
    force_remove, force_reinstall)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 145, in solve_for_diff
    force_remove)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 242, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 475, in _run_sat
    conflicting_specs = ssc.r.get_conflicting_specs(tuple(final_environment_specs))
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 852, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 356, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 244, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - pin_compatible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lfpy/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 1397, in build
    create_build_envs(m, notest)
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 1281, in create_build_envs
    raise e
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 1271, in create_build_envs
    channel_urls=tuple(m.config.channel_urls))
  File "/home/lfpy/anaconda3/lib/python3.7/site-packages/conda_build/environ.py", line 755, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'pin_compatible'}
```

**Comment by espenhgn** [comment]
LFPy and dependencies can now be installed via conda-forge:
```
conda config --add channels conda-forge 
conda install lfpy
```
We also provide conda environment files to create new environments from scratch with all dependencies needed for LFPy (macos/linux only):
```
git clone https://github.com/LFPy/LFPy.git
cd LFPy
conda env create -f conda_environment_macos.yml
conda activate lfpy
python setup.py install
```
